run:
  allow-parallel-runners: true
  go: '1.21'

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - exhaustivestruct
    - nonamedreturns
    - tagliatelle
    - exhaustruct
    - varnamelen
    - scopelint
    - depguard
    - gci

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
    enable-all: true
  funlen:
    lines: 70
    ignore-comments: true
  cyclop:
    max-complexity: 15
    skip-tests: true
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: cmd/decompose/main\.go
      linters:
        - forbidigo
    - path: internal/graph/docker\.go
      text: "G204" # G204: Subprocess launched with a potential tainted input
      linters:
        - gosec
    - path: internal/builder/json\.go
      linters:
        - errchkjson
    - path: internal/node/json\.go
      linters:
        - govet # fieldalignment issue, ignored for json readability
    - path: internal/builder/builder\.go
      linters:
        - ireturn
    - path: ._test\.go
      linters:
        - goerr113
        - ireturn
        - funlen
